FROM us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:optimism

RUN apk add --no-cache jq tshark

COPY entrypoint-l2-geth.sh /entrypoint.sh

VOLUME ["/db"]

ENTRYPOINT ["/bin/sh", "/entrypoint.sh"]
